"""
Multi-Language Support for kodark.io Bot
Supports 15 languages with full UI translations.
"""

# Supported languages with flag emojis
SUPPORTED_LANGUAGES = {
    "en": {"name": "English", "flag": "🇬🇧"},
    "tr": {"name": "Türkçe", "flag": "🇹🇷"},
    "es": {"name": "Español", "flag": "🇪🇸"},
    "pt": {"name": "Português", "flag": "🇧🇷"},
    "fr": {"name": "Français", "flag": "🇫🇷"},
    "de": {"name": "Deutsch", "flag": "🇩🇪"},
    "ru": {"name": "Русский", "flag": "🇷🇺"},
    "zh": {"name": "中文", "flag": "🇨🇳"},
    "ja": {"name": "日本語", "flag": "🇯🇵"},
    "ko": {"name": "한국어", "flag": "🇰🇷"},
    "ar": {"name": "العربية", "flag": "🇸🇦"},
    "hi": {"name": "हिन्दी", "flag": "🇮🇳"},
    "it": {"name": "Italiano", "flag": "🇮🇹"},
    "nl": {"name": "Nederlands", "flag": "🇳🇱"},
    "pl": {"name": "Polski", "flag": "🇵🇱"},
}

DEFAULT_LANG = "en"

# ==================== TRANSLATIONS ====================

TRANSLATIONS = {
    # ===== START MENU =====
    "start_title": {
        "en": "Welcome to kodark.io \u2660\ufe0f",
        "tr": "kodark.io'ya ho\u015f geldin \u2660\ufe0f",
        "es": "Bienvenido a kodark.io \u2660\ufe0f",
        "pt": "Bem-vindo ao kodark.io \u2660\ufe0f",
        "fr": "Bienvenue sur kodark.io \u2660\ufe0f",
        "de": "Willkommen bei kodark.io \u2660\ufe0f",
        "ru": "\u0414\u043e\u0431\u0440\u043e \u043f\u043e\u0436\u0430\u043b\u043e\u0432\u0430\u0442\u044c \u0432 kodark.io \u2660\ufe0f",
        "zh": "\u6b22\u8fce\u6765\u5230 kodark.io \u2660\ufe0f",
        "ja": "kodark.io \u3078\u3088\u3046\u3053\u305d \u2660\ufe0f",
        "ko": "kodark.io\uc5d0 \uc624\uc2e0 \uac83\uc744 \ud658\uc601\ud569\ub2c8\ub2e4 \u2660\ufe0f",
        "ar": "\u0645\u0631\u062d\u0628\u0627 \u0628\u0643 \u0641\u064a kodark.io \u2660\ufe0f",
        "hi": "kodark.io \u092e\u0947\u0902 \u0906\u092a\u0915\u093e \u0938\u094d\u0935\u093e\u0917\u0924 \u0939\u0948 \u2660\ufe0f",
        "it": "Benvenuto su kodark.io \u2660\ufe0f",
        "nl": "Welkom bij kodark.io \u2660\ufe0f",
        "pl": "Witamy w kodark.io \u2660\ufe0f",
    },
    "start_subtitle": {
        "en": "Scan any Solana memecoin before you ape in \u2666\ufe0f",
        "tr": "Yat\u0131r\u0131m yapmadan \u00f6nce herhangi bir Solana memecoin'i tara \u2666\ufe0f",
        "es": "Escanea cualquier memecoin de Solana antes de invertir \u2666\ufe0f",
        "pt": "Escaneie qualquer memecoin Solana antes de investir \u2666\ufe0f",
        "fr": "Scannez n'importe quel memecoin Solana avant d'investir \u2666\ufe0f",
        "de": "Scanne jeden Solana Memecoin bevor du investierst \u2666\ufe0f",
        "ru": "\u0421\u043a\u0430\u043d\u0438\u0440\u0443\u0439 \u043b\u044e\u0431\u043e\u0439 \u043c\u0435\u043c\u043a\u043e\u0438\u043d Solana \u043f\u0435\u0440\u0435\u0434 \u043f\u043e\u043a\u0443\u043f\u043a\u043e\u0439 \u2666\ufe0f",
        "zh": "\u5728\u6295\u8d44\u524d\u626b\u63cf\u4efb\u4f55 Solana \u6a21\u56e0\u5e01 \u2666\ufe0f",
        "ja": "\u6295\u8cc7\u524d\u306b\u3042\u3089\u3086\u308b Solana \u30df\u30fc\u30e0\u30b3\u30a4\u30f3\u3092\u30b9\u30ad\u30e3\u30f3 \u2666\ufe0f",
        "ko": "\ud22c\uc790 \uc804 \ubaa8\ub4e0 Solana \ubc00\ucf54\uc778\uc744 \uc2a4\uce94\ud558\uc138\uc694 \u2666\ufe0f",
        "ar": "\u0627\u0641\u062d\u0635 \u0623\u064a \u0639\u0645\u0644\u0629 \u0645\u064a\u0645 Solana \u0642\u0628\u0644 \u0627\u0644\u0627\u0633\u062a\u062b\u0645\u0627\u0631 \u2666\ufe0f",
        "hi": "\u0928\u093f\u0935\u0947\u0936 \u0938\u0947 \u092a\u0939\u0932\u0947 \u0915\u093f\u0938\u0940 \u092d\u0940 Solana \u092e\u0940\u092e\u0915\u0949\u0907\u0928 \u0915\u094b \u0938\u094d\u0915\u0948\u0928 \u0915\u0930\u0947\u0902 \u2666\ufe0f",
        "it": "Scansiona qualsiasi memecoin Solana prima di investire \u2666\ufe0f",
        "nl": "Scan elke Solana memecoin voordat je investeert \u2666\ufe0f",
        "pl": "Zeskanuj dowolny memecoin Solana przed inwestycj\u0105 \u2666\ufe0f",
    },
    "features_header": {
        "en": "What you can do with kodark.io \u2663\ufe0f",
        "tr": "kodark.io ile neler yapabilirsin \u2663\ufe0f",
        "es": "Qu\u00e9 puedes hacer con kodark.io \u2663\ufe0f",
        "pt": "O que voc\u00ea pode fazer com kodark.io \u2663\ufe0f",
        "fr": "Ce que vous pouvez faire avec kodark.io \u2663\ufe0f",
        "de": "Was du mit kodark.io machen kannst \u2663\ufe0f",
        "ru": "\u0427\u0442\u043e \u043c\u043e\u0436\u043d\u043e \u0434\u0435\u043b\u0430\u0442\u044c \u0441 kodark.io \u2663\ufe0f",
        "zh": "\u4f60\u53ef\u4ee5\u7528 kodark.io \u505a\u4ec0\u4e48 \u2663\ufe0f",
        "ja": "kodark.io \u3067\u3067\u304d\u308b\u3053\u3068 \u2663\ufe0f",
        "ko": "kodark.io\ub85c \ud560 \uc218 \uc788\ub294 \uac83 \u2663\ufe0f",
        "ar": "\u0645\u0627 \u064a\u0645\u0643\u0646\u0643 \u0641\u0639\u0644\u0647 \u0645\u0639 kodark.io \u2663\ufe0f",
        "hi": "kodark.io \u0915\u0947 \u0938\u093e\u0925 \u0906\u092a \u0915\u094d\u092f\u093e \u0915\u0930 \u0938\u0915\u0924\u0947 \u0939\u0948\u0902 \u2663\ufe0f",
        "it": "Cosa puoi fare con kodark.io \u2663\ufe0f",
        "nl": "Wat je kunt doen met kodark.io \u2663\ufe0f",
        "pl": "Co mo\u017cesz zrobi\u0107 z kodark.io \u2663\ufe0f",
    },
    "feature_whale": {
        "en": "Whale Watch — Track large wallet movements 🐋",
        "tr": "🐋 Balina Takibi — Büyük cüzdan hareketlerini izle",
        "es": "🐋 Rastreo de Ballenas — Rastrea movimientos de grandes billeteras",
        "pt": "🐋 Rastreio de Baleias — Rastreie movimentos de grandes carteiras",
        "fr": "🐋 Suivi des Baleines — Suivez les mouvements des gros portefeuilles",
        "de": "🐋 Wal-Tracking — Verfolge große Wallet-Bewegungen",
        "ru": "🐋 Отслеживание китов — Следи за крупными кошельками",
        "zh": "🐋 鲸鱼追踪 — 追踪大额钱包动向",
        "ja": "🐋 クジラ追跡 — 大口ウォレットの動きを追跡",
        "ko": "🐋 고래 추적 — 대형 지갑 움직임 추적",
        "ar": "🐋 تتبع الحيتان — تتبع حركات المحافظ الكبيرة",
        "hi": "🐋 व्हेल ट्रैकिंग — बड़े वॉलेट की गतिविधियां ट्रैक करें",
        "it": "🐋 Tracciamento Balene — Monitora i movimenti dei grandi portafogli",
        "nl": "🐋 Walvis Tracking — Volg grote wallet bewegingen",
        "pl": "🐋 Śledzenie Wielorybów — Śledź ruchy dużych portfeli",
    },
    "feature_risk": {
        "en": "Risk Assessment — Rug pull detection & security scan 🛡",
        "tr": "🛡 Risk Değerlendirmesi — Rug pull tespiti ve güvenlik taraması",
        "es": "🛡 Evaluación de Riesgos — Detección de rug pull y escaneo de seguridad",
        "pt": "🛡 Avaliação de Risco — Detecção de rug pull e varredura de segurança",
        "fr": "🛡 Évaluation des Risques — Détection de rug pull et scan de sécurité",
        "de": "🛡 Risikobewertung — Rug Pull Erkennung & Sicherheitsscan",
        "ru": "🛡 Оценка рисков — Обнаружение rug pull и сканирование безопасности",
        "zh": "🛡 风险评估 — Rug Pull检测和安全扫描",
        "ja": "🛡 リスク評価 — ラグプル検出とセキュリティスキャン",
        "ko": "🛡 위험 평가 — 러그풀 탐지 및 보안 스캔",
        "ar": "🛡 تقييم المخاطر — كشف الاحتيال ومسح الأمان",
        "hi": "🛡 जोखिम मूल्यांकन — रग पुल डिटेक्शन और सुरक्षा स्कैन",
        "it": "🛡 Valutazione Rischi — Rilevamento rug pull e scansione sicurezza",
        "nl": "🛡 Risicobeoordeling — Rug pull detectie & beveiligingsscan",
        "pl": "🛡 Ocena Ryzyka — Wykrywanie rug pull i skan bezpieczeństwa",
    },
    "feature_holder": {
        "en": "Holder Analysis — Top holder distribution & insiders 📊",
        "tr": "📊 Holder Analizi — Büyük holder dağılımı ve insider'lar",
        "es": "📊 Análisis de Holders — Distribución de holders principales e insiders",
        "pt": "📊 Análise de Holders — Distribuição dos principais holders e insiders",
        "fr": "📊 Analyse des Holders — Distribution des principaux holders et insiders",
        "de": "📊 Holder-Analyse — Top Holder Verteilung & Insider",
        "ru": "📊 Анализ холдеров — Распределение крупных холдеров и инсайдеров",
        "zh": "📊 持有者分析 — 顶级持有者分布和内部人员",
        "ja": "📊 ホルダー分析 — トップホルダー分布とインサイダー",
        "ko": "📊 홀더 분석 — 상위 홀더 분포 및 내부자",
        "ar": "📊 تحليل الحاملين — توزيع كبار الحاملين والمطلعين",
        "hi": "📊 होल्डर विश्लेषण — शीर्ष होल्डर वितरण और इनसाइडर",
        "it": "📊 Analisi Holders — Distribuzione top holders e insider",
        "nl": "📊 Holder Analyse — Top holder distributie & insiders",
        "pl": "📊 Analiza Holderów — Dystrybucja top holderów i insiderzy",
    },
    "feature_alarm": {
        "en": "Price Alarms — Get notified on price targets ⏰",
        "tr": "⏰ Fiyat Alarmları — Fiyat hedeflerinde bildirim al",
        "es": "⏰ Alarmas de Precio — Recibe notificaciones de precios objetivo",
        "pt": "⏰ Alarmes de Preço — Receba notificações de preços alvo",
        "fr": "⏰ Alarmes de Prix — Soyez notifié sur vos objectifs de prix",
        "de": "⏰ Preisalarme — Benachrichtigungen bei Kurszielen",
        "ru": "⏰ Ценовые оповещения — Уведомления о целевых ценах",
        "zh": "⏰ 价格警报 — 达到目标价格时通知",
        "ja": "⏰ 価格アラーム — 目標価格で通知",
        "ko": "⏰ 가격 알람 — 목표 가격 알림",
        "ar": "⏰ تنبيهات الأسعار — احصل على إشعارات عند الأسعار المستهدفة",
        "hi": "⏰ प्राइस अलार्म — लक्ष्य कीमतों पर सूचना प्राप्त करें",
        "it": "⏰ Allarmi Prezzo — Ricevi notifiche sui prezzi target",
        "nl": "⏰ Prijsalarmen — Ontvang meldingen bij koersdoelen",
        "pl": "⏰ Alarmy Cenowe — Otrzymuj powiadomienia o cenach docelowych",
    },
    "feature_sniper": {
        "en": "Auto-Sniper — New token launch alerts (Pump.fun, Raydium, Jupiter) 🎯",
        "tr": "🎯 Otomatik Sniper — Yeni token lansman uyarıları (Pump.fun, Raydium, Jupiter)",
        "es": "🎯 Auto-Sniper — Alertas de lanzamiento de nuevos tokens (Pump.fun, Raydium, Jupiter)",
        "pt": "🎯 Auto-Sniper — Alertas de lançamento de novos tokens (Pump.fun, Raydium, Jupiter)",
        "fr": "🎯 Auto-Sniper — Alertes de lancement de nouveaux tokens (Pump.fun, Raydium, Jupiter)",
        "de": "🎯 Auto-Sniper — Neue Token-Launch Benachrichtigungen (Pump.fun, Raydium, Jupiter)",
        "ru": "🎯 Авто-Снайпер — Уведомления о запуске новых токенов (Pump.fun, Raydium, Jupiter)",
        "zh": "🎯 自动狙击 — 新代币上线提醒 (Pump.fun, Raydium, Jupiter)",
        "ja": "🎯 オートスナイパー — 新トークンローンチアラート (Pump.fun, Raydium, Jupiter)",
        "ko": "🎯 오토 스나이퍼 — 신규 토큰 출시 알림 (Pump.fun, Raydium, Jupiter)",
        "ar": "🎯 القناص التلقائي — تنبيهات إطلاق التوكنات الجديدة (Pump.fun, Raydium, Jupiter)",
        "hi": "🎯 ऑटो-स्नाइपर — नए टोकन लॉन्च अलर्ट (Pump.fun, Raydium, Jupiter)",
        "it": "🎯 Auto-Sniper — Avvisi lancio nuovi token (Pump.fun, Raydium, Jupiter)",
        "nl": "🎯 Auto-Sniper — Nieuwe token lancering alerts (Pump.fun, Raydium, Jupiter)",
        "pl": "🎯 Auto-Sniper — Alerty nowych tokenów (Pump.fun, Raydium, Jupiter)",
    },
    "feature_chart": {
        "en": "Advanced Charts — Price charts inside Telegram 📉",
        "tr": "📉 Gelişmiş Grafikler — Telegram içinde fiyat grafikleri",
        "es": "📉 Gráficos Avanzados — Gráficos de precios dentro de Telegram",
        "pt": "📉 Gráficos Avançados — Gráficos de preços dentro do Telegram",
        "fr": "📉 Graphiques Avancés — Graphiques de prix dans Telegram",
        "de": "📉 Erweiterte Charts — Preischarts in Telegram",
        "ru": "📉 Продвинутые графики — Ценовые графики в Telegram",
        "zh": "📉 高级图表 — Telegram内价格图表",
        "ja": "📉 高度なチャート — Telegram内の価格チャート",
        "ko": "📉 고급 차트 — 텔레그램 내 가격 차트",
        "ar": "📉 رسوم بيانية متقدمة — رسوم بيانية للأسعار داخل تيليجرام",
        "hi": "📉 उन्नत चार्ट — टेलीग्राम के अंदर प्राइस चार्ट",
        "it": "📉 Grafici Avanzati — Grafici dei prezzi dentro Telegram",
        "nl": "📉 Geavanceerde Grafieken — Prijsgrafieken in Telegram",
        "pl": "📉 Zaawansowane Wykresy — Wykresy cenowe w Telegramie",
    },
    "feature_signals": {
        "en": "Market Signals — Fear & Greed, BTC Dom, SOL price 📈",
        "tr": "📈 Piyasa Sinyalleri — Korku & Açgözlülük, BTC Dom, SOL fiyat",
        "es": "📈 Señales de Mercado — Miedo y Codicia, Dom BTC, precio SOL",
        "pt": "📈 Sinais de Mercado — Medo e Ganância, Dom BTC, preço SOL",
        "fr": "📈 Signaux du Marché — Peur et Avidité, Dom BTC, prix SOL",
        "de": "📈 Marktsignale — Angst & Gier, BTC Dom, SOL Preis",
        "ru": "📈 Рыночные сигналы — Страх и Жадность, BTC Dom, цена SOL",
        "zh": "📈 市场信号 — 恐惧与贪婪, BTC主导, SOL价格",
        "ja": "📈 マーケットシグナル — 恐怖と貪欲, BTC Dom, SOL価格",
        "ko": "📈 시장 신호 — 공포와 탐욕, BTC 도미넌스, SOL 가격",
        "ar": "📈 إشارات السوق — الخوف والطمع، هيمنة BTC، سعر SOL",
        "hi": "📈 मार्केट सिग्नल — डर और लालच, BTC डोम, SOL कीमत",
        "it": "📈 Segnali di Mercato — Paura e Avidità, BTC Dom, prezzo SOL",
        "nl": "📈 Marktsignalen — Angst & Hebzucht, BTC Dom, SOL prijs",
        "pl": "📈 Sygnały Rynkowe — Strach i Chciwość, BTC Dom, cena SOL",
    },

    # ===== BUTTONS =====
    "btn_start_analyzing": {
        "en": "🃏 START ANALYZING",
        "tr": "🃏 ANALİZE BAŞLA",
        "es": "🃏 INICIAR ANÁLISIS",
        "pt": "🃏 INICIAR ANÁLISE",
        "fr": "🃏 COMMENCER L'ANALYSE",
        "de": "🃏 ANALYSE STARTEN",
        "ru": "🃏 НАЧАТЬ АНАЛИЗ",
        "zh": "🃏 开始分析",
        "ja": "🃏 分析開始",
        "ko": "🃏 분석 시작",
        "ar": "🃏 بدء التحليل",
        "hi": "🃏 विश्लेषण शुरू करें",
        "it": "🃏 INIZIA ANALISI",
        "nl": "🃏 START ANALYSE",
        "pl": "🃏 ROZPOCZNIJ ANALIZĘ",
    },
    "btn_market_signals": {
        "en": "📈 Market Signals",
        "tr": "📈 Piyasa Sinyalleri",
        "es": "📈 Señales de Mercado",
        "pt": "📈 Sinais de Mercado",
        "fr": "📈 Signaux du Marché",
        "de": "📈 Marktsignale",
        "ru": "📈 Рыночные сигналы",
        "zh": "📈 市场信号",
        "ja": "📈 マーケットシグナル",
        "ko": "📈 시장 신호",
        "ar": "📈 إشارات السوق",
        "hi": "📈 मार्केट सिग्नल",
        "it": "📈 Segnali di Mercato",
        "nl": "📈 Marktsignalen",
        "pl": "📈 Sygnały Rynkowe",
    },
    "btn_my_alarms": {
        "en": "⏰ My Alarms",
        "tr": "⏰ Alarmlarım",
        "es": "⏰ Mis Alarmas",
        "pt": "⏰ Meus Alarmes",
        "fr": "⏰ Mes Alarmes",
        "de": "⏰ Meine Alarme",
        "ru": "⏰ Мои оповещения",
        "zh": "⏰ 我的警报",
        "ja": "⏰ マイアラーム",
        "ko": "⏰ 내 알람",
        "ar": "⏰ تنبيهاتي",
        "hi": "⏰ मेरे अलार्म",
        "it": "⏰ I Miei Allarmi",
        "nl": "⏰ Mijn Alarmen",
        "pl": "⏰ Moje Alarmy",
    },
    "btn_whale_alerts": {
        "en": "🐋 My Whale Alerts",
        "tr": "🐋 Balina Uyarılarım",
        "es": "🐋 Mis Alertas de Ballenas",
        "pt": "🐋 Meus Alertas de Baleias",
        "fr": "🐋 Mes Alertes Baleines",
        "de": "🐋 Meine Wal-Alerts",
        "ru": "🐋 Мои оповещения о китах",
        "zh": "🐋 我的鲸鱼警报",
        "ja": "🐋 クジラアラート",
        "ko": "🐋 고래 알림",
        "ar": "🐋 تنبيهات الحيتان",
        "hi": "🐋 व्हेल अलर्ट",
        "it": "🐋 I Miei Avvisi Balene",
        "nl": "🐋 Mijn Walvis Alerts",
        "pl": "🐋 Moje Alerty Wielorybów",
    },
    "btn_sniper_alerts": {
        "en": "🎯 Sniper Alerts",
        "tr": "🎯 Sniper Uyarıları",
        "es": "🎯 Alertas Sniper",
        "pt": "🎯 Alertas Sniper",
        "fr": "🎯 Alertes Sniper",
        "de": "🎯 Sniper-Alerts",
        "ru": "🎯 Снайпер-оповещения",
        "zh": "🎯 狙击警报",
        "ja": "🎯 スナイパーアラート",
        "ko": "🎯 스나이퍼 알림",
        "ar": "🎯 تنبيهات القناص",
        "hi": "🎯 स्नाइपर अलर्ट",
        "it": "🎯 Avvisi Sniper",
        "nl": "🎯 Sniper Alerts",
        "pl": "🎯 Alerty Sniper",
    },
    "btn_premium": {
        "en": "💎 Premium Status",
        "tr": "💎 Premium Durumu",
        "es": "💎 Estado Premium",
        "pt": "💎 Status Premium",
        "fr": "💎 Statut Premium",
        "de": "💎 Premium Status",
        "ru": "💎 Премиум статус",
        "zh": "💎 高级状态",
        "ja": "💎 プレミアムステータス",
        "ko": "💎 프리미엄 상태",
        "ar": "💎 حالة بريميوم",
        "hi": "💎 प्रीमियम स्थिति",
        "it": "💎 Stato Premium",
        "nl": "💎 Premium Status",
        "pl": "💎 Status Premium",
    },
    "btn_roadmap": {
        "en": "🗺 Roadmap",
        "tr": "🗺 Yol Haritası",
        "es": "🗺 Hoja de Ruta",
        "pt": "🗺 Roteiro",
        "fr": "🗺 Feuille de Route",
        "de": "🗺 Roadmap",
        "ru": "🗺 Дорожная карта",
        "zh": "🗺 路线图",
        "ja": "🗺 ロードマップ",
        "ko": "🗺 로드맵",
        "ar": "🗺 خارطة الطريق",
        "hi": "🗺 रोडमैप",
        "it": "🗺 Roadmap",
        "nl": "🗺 Roadmap",
        "pl": "🗺 Mapa Drogowa",
    },
    "btn_language": {
        "en": "🌐 Language",
        "tr": "🌐 Dil",
        "es": "🌐 Idioma",
        "pt": "🌐 Idioma",
        "fr": "🌐 Langue",
        "de": "🌐 Sprache",
        "ru": "🌐 Язык",
        "zh": "🌐 语言",
        "ja": "🌐 言語",
        "ko": "🌐 언어",
        "ar": "🌐 اللغة",
        "hi": "🌐 भाषा",
        "it": "🌐 Lingua",
        "nl": "🌐 Taal",
        "pl": "🌐 Język",
    },
    "btn_home": {
        "en": "🏠 Main Menu",
        "tr": "🏠 Ana Menü",
        "es": "🏠 Menú Principal",
        "pt": "🏠 Menu Principal",
        "fr": "🏠 Menu Principal",
        "de": "🏠 Hauptmenü",
        "ru": "🏠 Главное меню",
        "zh": "🏠 主菜单",
        "ja": "🏠 メインメニュー",
        "ko": "🏠 메인 메뉴",
        "ar": "🏠 القائمة الرئيسية",
        "hi": "🏠 मुख्य मेनू",
        "it": "🏠 Menu Principale",
        "nl": "🏠 Hoofdmenu",
        "pl": "🏠 Menu Główne",
    },
    "btn_back": {
        "en": "◀️ Back",
        "tr": "◀️ Geri",
        "es": "◀️ Atrás",
        "pt": "◀️ Voltar",
        "fr": "◀️ Retour",
        "de": "◀️ Zurück",
        "ru": "◀️ Назад",
        "zh": "◀️ 返回",
        "ja": "◀️ 戻る",
        "ko": "◀️ 뒤로",
        "ar": "◀️ رجوع",
        "hi": "◀️ वापस",
        "it": "◀️ Indietro",
        "nl": "◀️ Terug",
        "pl": "◀️ Wstecz",
    },
    "btn_chart": {
        "en": "📉 Price Chart",
        "tr": "📉 Fiyat Grafiği",
        "es": "📉 Gráfico de Precios",
        "pt": "📉 Gráfico de Preços",
        "fr": "📉 Graphique des Prix",
        "de": "📉 Preischart",
        "ru": "📉 Ценовой график",
        "zh": "📉 价格图表",
        "ja": "📉 価格チャート",
        "ko": "📉 가격 차트",
        "ar": "📉 رسم بياني للأسعار",
        "hi": "📉 प्राइस चार्ट",
        "it": "📉 Grafico Prezzi",
        "nl": "📉 Prijsgrafiek",
        "pl": "📉 Wykres Cen",
    },

    "btn_wallet_tracker": {
        "en": "\U0001f50d Smart Money Tracker",
        "tr": "\U0001f50d Ak\u0131ll\u0131 Para Takip\u00e7isi",
        "es": "\U0001f50d Rastreador de Dinero Inteligente",
        "pt": "\U0001f50d Rastreador de Dinheiro Inteligente",
        "fr": "\U0001f50d Traqueur d'Argent Intelligent",
        "de": "\U0001f50d Smart Money Tracker",
        "ru": "\U0001f50d \u0422\u0440\u0435\u043a\u0435\u0440 \u0443\u043c\u043d\u044b\u0445 \u0434\u0435\u043d\u0435\u0433",
        "zh": "\U0001f50d \u667a\u80fd\u8d44\u91d1\u8ffd\u8e2a\u5668",
        "ja": "\U0001f50d \u30b9\u30de\u30fc\u30c8\u30de\u30cd\u30fc\u30c8\u30e9\u30c3\u30ab\u30fc",
        "ko": "\U0001f50d \uc2a4\ub9c8\ud2b8\uba38\ub2c8 \ud2b8\ub798\ucee4",
        "ar": "\U0001f50d \u0645\u062a\u062a\u0628\u0639 \u0627\u0644\u0623\u0645\u0648\u0627\u0644 \u0627\u0644\u0630\u0643\u064a\u0629",
        "hi": "\U0001f50d \u0938\u094d\u092e\u093e\u0930\u094d\u091f \u092e\u0928\u0940 \u091f\u094d\u0930\u0948\u0915\u0930",
        "it": "\U0001f50d Tracker Smart Money",
        "nl": "\U0001f50d Smart Money Tracker",
        "pl": "\U0001f50d \u015aledzenie Smart Money",
    },
    "btn_daily_summary": {
        "en": "\U0001f4ca Daily Summary",
        "tr": "\U0001f4ca G\u00fcnl\u00fck \u00d6zet",
        "es": "\U0001f4ca Resumen Diario",
        "pt": "\U0001f4ca Resumo Di\u00e1rio",
        "fr": "\U0001f4ca R\u00e9sum\u00e9 Quotidien",
        "de": "\U0001f4ca T\u00e4gliche Zusammenfassung",
        "ru": "\U0001f4ca \u0415\u0436\u0435\u0434\u043d\u0435\u0432\u043d\u044b\u0439 \u043e\u0431\u0437\u043e\u0440",
        "zh": "\U0001f4ca \u6bcf\u65e5\u6458\u8981",
        "ja": "\U0001f4ca \u30c7\u30a4\u30ea\u30fc\u30b5\u30de\u30ea\u30fc",
        "ko": "\U0001f4ca \uc77c\uc77c \uc694\uc57d",
        "ar": "\U0001f4ca \u0627\u0644\u0645\u0644\u062e\u0635 \u0627\u0644\u064a\u0648\u0645\u064a",
        "hi": "\U0001f4ca \u0926\u0948\u0928\u093f\u0915 \u0938\u093e\u0930\u093e\u0902\u0936",
        "it": "\U0001f4ca Riepilogo Giornaliero",
        "nl": "\U0001f4ca Dagelijks Overzicht",
        "pl": "\U0001f4ca Podsumowanie Dnia",
    },

    # ===== COMMON TEXTS =====
    "premium_active": {
        "en": "✅ Premium Status: Active",
        "tr": "✅ Premium Durumu: Aktif",
        "es": "✅ Estado Premium: Activo",
        "pt": "✅ Status Premium: Ativo",
        "fr": "✅ Statut Premium: Actif",
        "de": "✅ Premium Status: Aktiv",
        "ru": "✅ Премиум статус: Активен",
        "zh": "✅ 高级状态: 已激活",
        "ja": "✅ プレミアムステータス: アクティブ",
        "ko": "✅ 프리미엄 상태: 활성",
        "ar": "✅ حالة بريميوم: نشط",
        "hi": "✅ प्रीमियम स्थिति: सक्रिय",
        "it": "✅ Stato Premium: Attivo",
        "nl": "✅ Premium Status: Actief",
        "pl": "✅ Status Premium: Aktywny",
    },
    "premium_inactive": {
        "en": "❌ Premium Status: Inactive",
        "tr": "❌ Premium Durumu: Pasif",
        "es": "❌ Estado Premium: Inactivo",
        "pt": "❌ Status Premium: Inativo",
        "fr": "❌ Statut Premium: Inactif",
        "de": "❌ Premium Status: Inaktiv",
        "ru": "❌ Премиум статус: Неактивен",
        "zh": "❌ 高级状态: 未激活",
        "ja": "❌ プレミアムステータス: 非アクティブ",
        "ko": "❌ 프리미엄 상태: 비활성",
        "ar": "❌ حالة بريميوم: غير نشط",
        "hi": "❌ प्रीमियम स्थिति: निष्क्रिय",
        "it": "❌ Stato Premium: Inattivo",
        "nl": "❌ Premium Status: Inactief",
        "pl": "❌ Status Premium: Nieaktywny",
    },
    "lifetime": {
        "en": "Lifetime",
        "tr": "Ömür Boyu",
        "es": "De por vida",
        "pt": "Vitalício",
        "fr": "À vie",
        "de": "Lebenslang",
        "ru": "Пожизненно",
        "zh": "终身",
        "ja": "永久",
        "ko": "평생",
        "ar": "مدى الحياة",
        "hi": "आजीवन",
        "it": "A vita",
        "nl": "Levenslang",
        "pl": "Dożywotni",
    },
    "select_option": {
        "en": "Select an option to get started \u2660\ufe0f",
        "tr": "👇 Başlamak için bir seçenek seçin:",
        "es": "👇 Selecciona una opción para comenzar:",
        "pt": "👇 Selecione uma opção para começar:",
        "fr": "👇 Sélectionnez une option pour commencer:",
        "de": "👇 Wähle eine Option zum Starten:",
        "ru": "👇 Выберите опцию для начала:",
        "zh": "👇 选择一个选项开始:",
        "ja": "👇 オプションを選択して開始:",
        "ko": "👇 시작할 옵션을 선택하세요:",
        "ar": "👇 اختر خيارًا للبدء:",
        "hi": "👇 शुरू करने के लिए एक विकल्प चुनें:",
        "it": "👇 Seleziona un'opzione per iniziare:",
        "nl": "👇 Selecteer een optie om te beginnen:",
        "pl": "👇 Wybierz opcję, aby rozpocząć:",
    },
    "type_address": {
        "en": "Type a Solana memecoin address below:",
        "tr": "Aşağıya bir Solana memecoin adresi yazın:",
        "es": "Escribe una dirección de memecoin Solana abajo:",
        "pt": "Digite um endereço de memecoin Solana abaixo:",
        "fr": "Tapez une adresse de memecoin Solana ci-dessous:",
        "de": "Gib eine Solana Memecoin-Adresse ein:",
        "ru": "Введите адрес мемкоина Solana ниже:",
        "zh": "在下方输入Solana Meme币地址:",
        "ja": "以下にSolanaミームコインアドレスを入力:",
        "ko": "아래에 솔라나 밈코인 주소를 입력하세요:",
        "ar": "اكتب عنوان عملة ميم سولانا أدناه:",
        "hi": "नीचे एक सोलाना मीमकॉइन पता टाइप करें:",
        "it": "Digita un indirizzo memecoin Solana qui sotto:",
        "nl": "Typ hieronder een Solana memecoin adres:",
        "pl": "Wpisz adres memecoina Solana poniżej:",
    },
    "token_found": {
        "en": "🃏 TOKEN FOUND",
        "tr": "🃏 TOKEN BULUNDU",
        "es": "🃏 TOKEN ENCONTRADO",
        "pt": "🃏 TOKEN ENCONTRADO",
        "fr": "🃏 TOKEN TROUVÉ",
        "de": "🃏 TOKEN GEFUNDEN",
        "ru": "🃏 ТОКЕН НАЙДЕН",
        "zh": "🃏 找到代币",
        "ja": "🃏 トークン発見",
        "ko": "🃏 토큰 발견",
        "ar": "🃏 تم العثور على التوكن",
        "hi": "🃏 टोकन मिला",
        "it": "🃏 TOKEN TROVATO",
        "nl": "🃏 TOKEN GEVONDEN",
        "pl": "🃏 TOKEN ZNALEZIONY",
    },
    "what_to_do": {
        "en": "What would you like to do?",
        "tr": "Ne yapmak istersiniz?",
        "es": "¿Qué te gustaría hacer?",
        "pt": "O que você gostaria de fazer?",
        "fr": "Que souhaitez-vous faire?",
        "de": "Was möchtest du tun?",
        "ru": "Что вы хотите сделать?",
        "zh": "你想做什么？",
        "ja": "何をしますか？",
        "ko": "무엇을 하시겠습니까?",
        "ar": "ماذا تريد أن تفعل؟",
        "hi": "आप क्या करना चाहेंगे?",
        "it": "Cosa vorresti fare?",
        "nl": "Wat wil je doen?",
        "pl": "Co chciałbyś zrobić?",
    },
    "analysis_progress": {
        "en": "⏳ Analysis in progress...\n\n🔄 Fetching DexScreener data...\n🔄 Running RugCheck security scan...\n🔄 Analyzing whale & holder data...\n🔄 Generating comprehensive report...",
        "tr": "⏳ Analiz devam ediyor...\n\n🔄 DexScreener verileri alınıyor...\n🔄 RugCheck güvenlik taraması yapılıyor...\n🔄 Balina ve holder verileri analiz ediliyor...\n🔄 Kapsamlı rapor oluşturuluyor...",
        "es": "⏳ Análisis en progreso...\n\n🔄 Obteniendo datos de DexScreener...\n🔄 Ejecutando escaneo de seguridad RugCheck...\n🔄 Analizando datos de ballenas y holders...\n🔄 Generando informe completo...",
        "pt": "⏳ Análise em andamento...\n\n🔄 Buscando dados do DexScreener...\n🔄 Executando varredura de segurança RugCheck...\n🔄 Analisando dados de baleias e holders...\n🔄 Gerando relatório completo...",
        "fr": "⏳ Analyse en cours...\n\n🔄 Récupération des données DexScreener...\n🔄 Scan de sécurité RugCheck en cours...\n🔄 Analyse des données baleines et holders...\n🔄 Génération du rapport complet...",
        "de": "⏳ Analyse läuft...\n\n🔄 DexScreener Daten werden abgerufen...\n🔄 RugCheck Sicherheitsscan läuft...\n🔄 Wal- und Holder-Daten werden analysiert...\n🔄 Umfassender Bericht wird erstellt...",
        "ru": "⏳ Анализ выполняется...\n\n🔄 Получение данных DexScreener...\n🔄 Запуск проверки безопасности RugCheck...\n🔄 Анализ данных китов и холдеров...\n🔄 Создание полного отчета...",
        "zh": "⏳ 分析进行中...\n\n🔄 获取DexScreener数据...\n🔄 运行RugCheck安全扫描...\n🔄 分析鲸鱼和持有者数据...\n🔄 生成综合报告...",
        "ja": "⏳ 分析中...\n\n🔄 DexScreenerデータ取得中...\n🔄 RugCheckセキュリティスキャン実行中...\n🔄 クジラ＆ホルダーデータ分析中...\n🔄 総合レポート生成中...",
        "ko": "⏳ 분석 진행 중...\n\n🔄 DexScreener 데이터 가져오는 중...\n🔄 RugCheck 보안 스캔 실행 중...\n🔄 고래 및 홀더 데이터 분석 중...\n🔄 종합 보고서 생성 중...",
        "ar": "⏳ التحليل قيد التقدم...\n\n🔄 جلب بيانات DexScreener...\n🔄 تشغيل فحص أمان RugCheck...\n🔄 تحليل بيانات الحيتان والحاملين...\n🔄 إنشاء تقرير شامل...",
        "hi": "⏳ विश्लेषण प्रगति पर...\n\n🔄 DexScreener डेटा प्राप्त हो रहा है...\n🔄 RugCheck सुरक्षा स्कैन चल रहा है...\n🔄 व्हेल और होल्डर डेटा का विश्लेषण...\n🔄 व्यापक रिपोर्ट तैयार हो रही है...",
        "it": "⏳ Analisi in corso...\n\n🔄 Recupero dati DexScreener...\n🔄 Scansione sicurezza RugCheck in corso...\n🔄 Analisi dati balene e holders...\n🔄 Generazione report completo...",
        "nl": "⏳ Analyse bezig...\n\n🔄 DexScreener data ophalen...\n🔄 RugCheck beveiligingsscan uitvoeren...\n🔄 Walvis & holder data analyseren...\n🔄 Uitgebreid rapport genereren...",
        "pl": "⏳ Analiza w toku...\n\n🔄 Pobieranie danych DexScreener...\n🔄 Uruchamianie skanu bezpieczeństwa RugCheck...\n🔄 Analiza danych wielorybów i holderów...\n🔄 Generowanie kompleksowego raportu...",
    },
    "lang_select": {
        "en": "🌐 SELECT LANGUAGE\n\nChoose your preferred language:",
        "tr": "🌐 DİL SEÇİN\n\nTercih ettiğiniz dili seçin:",
        "es": "🌐 SELECCIONAR IDIOMA\n\nElige tu idioma preferido:",
        "pt": "🌐 SELECIONAR IDIOMA\n\nEscolha seu idioma preferido:",
        "fr": "🌐 SÉLECTIONNER LA LANGUE\n\nChoisissez votre langue préférée:",
        "de": "🌐 SPRACHE WÄHLEN\n\nWähle deine bevorzugte Sprache:",
        "ru": "🌐 ВЫБЕРИТЕ ЯЗЫК\n\nВыберите предпочитаемый язык:",
        "zh": "🌐 选择语言\n\n选择您的首选语言:",
        "ja": "🌐 言語選択\n\nご希望の言語を選択してください:",
        "ko": "🌐 언어 선택\n\n원하는 언어를 선택하세요:",
        "ar": "🌐 اختر اللغة\n\nاختر لغتك المفضلة:",
        "hi": "🌐 भाषा चुनें\n\nअपनी पसंदीदा भाषा चुनें:",
        "it": "🌐 SELEZIONA LINGUA\n\nScegli la tua lingua preferita:",
        "nl": "🌐 TAAL SELECTEREN\n\nKies je voorkeurstaal:",
        "pl": "🌐 WYBIERZ JĘZYK\n\nWybierz preferowany język:",
    },
    "lang_changed": {
        "en": "✅ Language changed to English!",
        "tr": "✅ Dil Türkçe olarak değiştirildi!",
        "es": "✅ ¡Idioma cambiado a Español!",
        "pt": "✅ Idioma alterado para Português!",
        "fr": "✅ Langue changée en Français!",
        "de": "✅ Sprache auf Deutsch geändert!",
        "ru": "✅ Язык изменен на Русский!",
        "zh": "✅ 语言已更改为中文！",
        "ja": "✅ 言語が日本語に変更されました！",
        "ko": "✅ 언어가 한국어로 변경되었습니다!",
        "ar": "✅ تم تغيير اللغة إلى العربية!",
        "hi": "✅ भाषा हिन्दी में बदल दी गई!",
        "it": "✅ Lingua cambiata in Italiano!",
        "nl": "✅ Taal gewijzigd naar Nederlands!",
        "pl": "✅ Język zmieniony na Polski!",
    },
    "free_tier_info": {
        "en": "🆓 Free: {analyses} analyses + {alarms} alarms included!",
        "tr": "🆓 Ücretsiz: {analyses} analiz + {alarms} alarm dahil!",
        "es": "🆓 Gratis: {analyses} análisis + {alarms} alarmas incluidas!",
        "pt": "🆓 Grátis: {analyses} análises + {alarms} alarmes incluídos!",
        "fr": "🆓 Gratuit: {analyses} analyses + {alarms} alarmes incluses!",
        "de": "🆓 Kostenlos: {analyses} Analysen + {alarms} Alarme inklusive!",
        "ru": "🆓 Бесплатно: {analyses} анализов + {alarms} оповещений!",
        "zh": "🆓 免费: {analyses} 次分析 + {alarms} 个警报！",
        "ja": "🆓 無料: {analyses} 回の分析 + {alarms} 個のアラーム！",
        "ko": "🆓 무료: {analyses}회 분석 + {alarms}개 알람 포함!",
        "ar": "🆓 مجاني: {analyses} تحليلات + {alarms} تنبيهات!",
        "hi": "🆓 मुफ्त: {analyses} विश्लेषण + {alarms} अलार्म शामिल!",
        "it": "🆓 Gratis: {analyses} analisi + {alarms} allarmi inclusi!",
        "nl": "🆓 Gratis: {analyses} analyses + {alarms} alarmen inbegrepen!",
        "pl": "🆓 Bezpłatnie: {analyses} analiz + {alarms} alarmów w zestawie!",
    },
    "sniper_title": {
        "en": "🎯 AUTO-SNIPER ALERTS",
        "tr": "🎯 OTOMATİK SNİPER UYARILARI",
        "es": "🎯 ALERTAS AUTO-SNIPER",
        "pt": "🎯 ALERTAS AUTO-SNIPER",
        "fr": "🎯 ALERTES AUTO-SNIPER",
        "de": "🎯 AUTO-SNIPER BENACHRICHTIGUNGEN",
        "ru": "🎯 АВТО-СНАЙПЕР ОПОВЕЩЕНИЯ",
        "zh": "🎯 自动狙击警报",
        "ja": "🎯 オートスナイパーアラート",
        "ko": "🎯 오토 스나이퍼 알림",
        "ar": "🎯 تنبيهات القناص التلقائي",
        "hi": "🎯 ऑटो-स्नाइपर अलर्ट",
        "it": "🎯 AVVISI AUTO-SNIPER",
        "nl": "🎯 AUTO-SNIPER ALERTS",
        "pl": "🎯 ALERTY AUTO-SNIPER",
    },
    "sniper_desc": {
        "en": "Get notified when new tokens launch on Solana.\nChoose which platforms to monitor:",
        "tr": "Solana'da yeni tokenler çıktığında bildirim alın.\nHangi platformları izlemek istediğinizi seçin:",
        "es": "Recibe notificaciones cuando se lancen nuevos tokens en Solana.\nElige qué plataformas monitorear:",
        "pt": "Receba notificações quando novos tokens forem lançados na Solana.\nEscolha quais plataformas monitorar:",
        "fr": "Soyez notifié quand de nouveaux tokens sont lancés sur Solana.\nChoisissez les plateformes à surveiller:",
        "de": "Werde benachrichtigt wenn neue Token auf Solana starten.\nWähle welche Plattformen überwacht werden sollen:",
        "ru": "Получайте уведомления о запуске новых токенов на Solana.\nВыберите платформы для мониторинга:",
        "zh": "当Solana上有新代币上线时获取通知。\n选择要监控的平台:",
        "ja": "Solanaで新しいトークンがローンチされた時に通知を受け取ります。\n監視するプラットフォームを選択:",
        "ko": "솔라나에서 새 토큰이 출시될 때 알림을 받으세요.\n모니터링할 플랫폼을 선택하세요:",
        "ar": "احصل على إشعارات عند إطلاق توكنات جديدة على سولانا.\nاختر المنصات التي تريد مراقبتها:",
        "hi": "सोलाना पर नए टोकन लॉन्च होने पर सूचना प्राप्त करें।\nमॉनिटर करने के लिए प्लेटफॉर्म चुनें:",
        "it": "Ricevi notifiche quando nuovi token vengono lanciati su Solana.\nScegli quali piattaforme monitorare:",
        "nl": "Ontvang meldingen wanneer nieuwe tokens worden gelanceerd op Solana.\nKies welke platforms je wilt monitoren:",
        "pl": "Otrzymuj powiadomienia o nowych tokenach na Solanie.\nWybierz platformy do monitorowania:",
    },
}


# ==================== HELPER FUNCTIONS ====================

def get_text(key: str, lang: str = DEFAULT_LANG, **kwargs) -> str:
    """Get translated text for a given key and language."""
    translations = TRANSLATIONS.get(key, {})
    text = translations.get(lang, translations.get(DEFAULT_LANG, f"[{key}]"))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text


def get_lang_name(lang_code: str) -> str:
    """Get the display name for a language code."""
    lang_info = SUPPORTED_LANGUAGES.get(lang_code, {})
    return f"{lang_info.get('flag', '')} {lang_info.get('name', lang_code)}"


def get_all_lang_buttons() -> list:
    """Get list of (flag+name, lang_code) tuples for language selection buttons."""
    buttons = []
    for code, info in SUPPORTED_LANGUAGES.items():
        buttons.append((f"{info['flag']} {info['name']}", f"lang_{code}"))
    return buttons
